config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'top#index'

  resources :groups, except: [:show,:index, :destroy] do
    resources :messages, only: [:index, :create]
  end
  resources :users, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  validates_presence_of :name
  has_many :users, through: :user_groups
  has_many :user_groups
  has_many :messages
  accepts_nested_attributes_for :user_groups

  def find_last_message
    messages.order('created_at DESC').last
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group
  validates_presence_of :body
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :groups, through: :user_groups
  has_many :user_groups

  scope :including_name_or_kana, ->(reg){ where("name like ?", reg).or where("kana like ?", reg) }
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  before_action :set_group_update, only: [:edit, :update]
  before_action :set_group_new, only: [:new, :create]

  def new; end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to group_messages_path(@group), notice: 'グループが作成されました。'
    else
      flash.now[:alert] = 'グループが作成されませんでした。'
      render action: :new
    end
  end

  def edit; end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: 'グループが更新されました。'
    else
      flash.now[:alert] = 'グループが更新されませんでした。'
      render action: :edit
    end
  end
  
  private
  def group_params
    params.require(:group).permit(:name, { :user_ids => [] })
  end

  def set_group_new
    @group = Group.new
    @users = User.all
  end

  def set_group_update
    @group = Group.find(params[:id])
    @users = User.all
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :store_messages_instance

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
    respond_to do |format|
      format.html { render :index}
      format.json { render "messages_update.json.jbuilder"}
    end
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to group_messages_path, notice: 'メッセージが投稿されました。' }
        format.json { render "message_index.json.jbuilder" }
      end
    else
      flash.now[:alert] = @message.errors.full_messages.first
      render :index
    end
  end

  private
  def message_params
    params.require(:message).permit(:body, :image).merge(group_id: params[:group_id], user_id: current_user.id)
  end

  def store_messages_instance
    @group = Group.find(params[:group_id])
    @groups = current_user.groups
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController

  def index
    @user = current_user
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    reg = params[:search_character]
    @users = User.including_name_or_kana(reg)
    render 'search_results', formats: [:json], handlers: [:jbuilder]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_shared.html.haml
.chat-group-form
  - if flag
    %h1 新規チャットグループ
  - else
    %h1 チャットグループ編集
  = form_for(group) do |f|
    .chat-group-form__field
      .chat-group-form__field--left
        = f.label :name, 'グループ名', class: "chat-group-form__label"
      .chat-group-form__field--right
        - if flag
          = f.text_field :name, placeholder: "グループ名を入力してください", id: "chat-group-name", class: "chat-group-form__input"
        - else
          = f.text_field :name, value: group.name, id: "chat_group_name", class: "chat-group-form__input"
    .chat-group-form__field
      .chat-group-form__field--left
        = f.label :users, "チャットメンバーを追加", class: "chat-group-form__label"
      .chat-group-form__field--right
        .chat-group-form__search
          = collection_check_boxes(:group, :user_ids, users, :id, :name)
        #user-search-result
    .chat-group-form__field
      .chat-group-form__field--left
        = f.label :name, "チャットメンバー", class: "chat-group-form__label"
      -if flag
        .chat-group-form__field--right
          #chat-group-users
            #chat-group-users-22.chat-group-user
            -# 暫定的に下記の実装
              %p.chat-group-user__name seo_kyohei
    .chat-group-form__field
      .chat-group-form__field--left
      .chat-group-form__field--right
        = f.submit "Save", class: "chat-group-form__action-btn", disable_with: "save"

app/views/groups/_shared_group_form.html.haml
.chat-group-form
  %h1= group.new_record? ? '新規チャットグループ' : 'チャットグループ編集'
  = form_for(group) do |f|
    .chat-group-form__field
      .chat-group-form__field--left
        = f.label :name, 'グループ名', class: "chat-group-form__label"
      .chat-group-form__field--right
        = f.text_field :name, placeholder: "グループ名を入力してください", id: "chat-group-name", class: "chat-group-form__input"
    .chat-group-form__field
      .chat-group-form__field--left
        = f.label :user_ids, "チャットメンバーを追加", class: "chat-group-form__label"
      .chat-group-form__field--right
        .chat-group-form__search
          = text_field_tag "chat-member-name", "",placeholder: "追加したいメンバーの名前を入力してください。", class: "chat-group-form__input"
          #user-search-hidden
            = collection_check_boxes(:group, :user_ids, users, :id, :name)
        #user-search-result
    .chat-group-form__field
      .chat-group-form__field--left
        = f.label :name, "チャットメンバー", class: "chat-group-form__label"
      -if group.new_record?
        .chat-group-form__field--right
          #chat-group-users
            #chat-group-users-22.chat-group-user
    .chat-group-form__field
      .chat-group-form__field--left
      .chat-group-form__field--right
        = f.submit "Save", class: "chat-group-form__action-btn", disable_with: "save"

app/views/groups/edit.html.haml
= render partial: "shared_group_form", locals: {group: @group, users: @users}

app/views/groups/new.html.haml
= render partial: "shared_group_form", locals: {group: @group, users: @users}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    - flash.each do |key, value|
      =content_tag :div, value, :class => "flash #{key}" unless value.blank?

    = yield

app/views/messages/_message.html.haml
.chat-space__tweet
  %p.tweet--name= message.user.name
  %p.tweet--time= message.created_at.strftime('%Y年%m月%d日 %H:%M:%S')
  %p.tweet= message.body

app/views/messages/index.html.haml
.container
  = render partial: '/shared/left-content'
  .right-contents
    .selected-group
      .selected-group__name
        %h2= @group.name
        %ul
          %li Menbers:
          - @group.users.each do |user|
            %li= user.name
      =link_to "Edit", edit_group_path(@group), class: "edit"
    .right-contents__chat-space
      = render partial: 'message', collection: @messages
    .chat-space__writeme
      = form_for ([@group, @message]), html: { class: 'js-form' } do |f|
        = f.text_field :body, placeholder: "   type a message", class: "text js-form__text-field"
        = f.submit "send", class: "send"
        = f.file_field :image, style: "display: none;", id: "file_input_origin"
        = fa_icon("image 2x", id: "file_input")

app/views/shared/_group.html.haml
.group-menu__content
  =link_to group.name, group_messages_path(group)
  - if group.find_last_message.present?
    %p= group.find_last_message.body
  - else
    %p= "まだ新着メッセージがありません。"

app/views/shared/_left-content.html.haml
.left-contents
  .user-menu
    %h2= current_user.name
    =link_to fa_icon("cog 2x"),edit_user_registration_path
    =link_to fa_icon("edit 2x"), new_group_path
  .group-menu
    = render partial: '/shared/group', collection: @groups

app/views/top/index.html.haml
.container
  = render partial: '/shared/left-content'
  .right-contents
    .selected-group
      .selected-group__name
        %h2 sampleグループ
        %p Menbers: sample太郎, sample子, sample平
      =link_to "Edit",'',class: "edit"
    .right-contents__chat-space
      .chat-space__tweet
        %p.tweet--name sample太郎
        %p.tweet--time 2017/02/24 15:42
        %p.tweet say sample
      .chat-space__writeme
        = form_for('') do |f|
          = f.text_field :message, placeholder: "   type a message", class: "text"
          = f.submit "send", class: "send"
        = link_to fa_icon("image 2x")